package none.todolist.user;

import java.time.LocalDateTime;
import java.util.UUID;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.Data;

//Setters and Getters are generated by lombok
@Data
// Create a table named tb_users
@Entity(name = "tb_users")
public class UserModel {

    // Generate a UUID for each user
    @Id
    @GeneratedValue(generator = "UUID")
    private UUID id;

    // Create a column named username
    // This column must be unique
    @Column(unique = true)
    private String username;
    private String name;
    private String password;

    @CreationTimestamp
    private LocalDateTime createdAt;
}
